import type {
  GSCCandidate,
  LostKeyword,
  Competitor,
  LLMAnalysis,
} from "./types";

// ── Mock GSC Properties ──
export const mockGSCSites = [
  { siteUrl: "https://www.example-agency.com", permissionLevel: "siteOwner" },
  { siteUrl: "https://blog.example-agency.com", permissionLevel: "siteFullUser" },
  { siteUrl: "sc-domain:example-agency.com", permissionLevel: "siteOwner" },
];

// ── Mock GSC Candidates ──
// Covers scenarios: big drop + important, drop but not important, cannibalization, etc.
export const mockCandidates: GSCCandidate[] = [
  {
    url: "https://www.example-agency.com/blog/headless-cms-comparison-2025",
    impressionsA: 4200,
    impressionsB: 9800,
    impressionsDiff: -5600,
    clicksA: 89,
    clicksB: 245,
    clicksDiffPercent: -63.7,
    positionA: 14.2,
    positionB: 5.7,
    positionDiff: 8.5,
    ctrA: 0.021,
    ctrB: 0.025,
    ctrDiff: -0.004,
    isImportant: true,
    topicMatch: "headless cms",
    hasCannibalization: false,
  },
  {
    url: "https://www.example-agency.com/blog/sanity-cms-nextjs-tutorial",
    impressionsA: 3100,
    impressionsB: 7200,
    impressionsDiff: -4100,
    clicksA: 62,
    clicksB: 189,
    clicksDiffPercent: -67.2,
    positionA: 11.8,
    positionB: 4.3,
    positionDiff: 7.5,
    ctrA: 0.02,
    ctrB: 0.026,
    ctrDiff: -0.006,
    isImportant: true,
    topicMatch: "sanity, nextjs",
    hasCannibalization: true,
    cannibalizingUrl: "https://www.example-agency.com/blog/getting-started-sanity-nextjs",
  },
  {
    url: "https://www.example-agency.com/blog/seo-ai-content-optimization",
    impressionsA: 2800,
    impressionsB: 6500,
    impressionsDiff: -3700,
    clicksA: 45,
    clicksB: 156,
    clicksDiffPercent: -71.2,
    positionA: 18.4,
    positionB: 7.1,
    positionDiff: 11.3,
    ctrA: 0.016,
    ctrB: 0.024,
    ctrDiff: -0.008,
    isImportant: true,
    topicMatch: "seo, ai",
    hasCannibalization: false,
  },
  {
    url: "https://www.example-agency.com/blog/cms-migration-guide-2025",
    impressionsA: 1800,
    impressionsB: 4600,
    impressionsDiff: -2800,
    clicksA: 28,
    clicksB: 98,
    clicksDiffPercent: -71.4,
    positionA: 15.6,
    positionB: 6.8,
    positionDiff: 8.8,
    ctrA: 0.016,
    ctrB: 0.021,
    ctrDiff: -0.006,
    isImportant: true,
    topicMatch: "cms, migration",
    hasCannibalization: false,
  },
  {
    url: "https://www.example-agency.com/blog/nextjs-performance-optimization",
    impressionsA: 5200,
    impressionsB: 8900,
    impressionsDiff: -3700,
    clicksA: 210,
    clicksB: 312,
    clicksDiffPercent: -32.7,
    positionA: 6.2,
    positionB: 3.8,
    positionDiff: 2.4,
    ctrA: 0.04,
    ctrB: 0.035,
    ctrDiff: 0.005,
    isImportant: true,
    topicMatch: "nextjs",
    hasCannibalization: false,
  },
  // NOT important — topic doesn't match
  {
    url: "https://www.example-agency.com/blog/remote-work-productivity-tips",
    impressionsA: 1200,
    impressionsB: 3800,
    impressionsDiff: -2600,
    clicksA: 15,
    clicksB: 67,
    clicksDiffPercent: -77.6,
    positionA: 22.1,
    positionB: 9.4,
    positionDiff: 12.7,
    ctrA: 0.013,
    ctrB: 0.018,
    ctrDiff: -0.005,
    isImportant: false,
    topicMatch: null,
    hasCannibalization: false,
  },
  // Borderline — small drop, doesn't meet threshold but included for context
  {
    url: "https://www.example-agency.com/blog/react-server-components-guide",
    impressionsA: 6800,
    impressionsB: 7100,
    impressionsDiff: -300,
    clicksA: 340,
    clicksB: 355,
    clicksDiffPercent: -4.2,
    positionA: 4.1,
    positionB: 3.9,
    positionDiff: 0.2,
    ctrA: 0.05,
    ctrB: 0.05,
    ctrDiff: 0,
    isImportant: true,
    topicMatch: "nextjs",
    hasCannibalization: false,
  },
];

// ── Mock Lost Keywords ──
export const mockLostKeywords: LostKeyword[] = [
  // For headless-cms-comparison-2025
  {
    keyword: "headless cms comparison",
    volume: 2400,
    position: 15,
    positionBefore: 4,
    traffic: 12,
    trafficChange: -380,
    kd: 42,
    valueScore: 1162.9,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/headless-cms-comparison-2025",
  },
  {
    keyword: "best headless cms 2025",
    volume: 1800,
    position: 18,
    positionBefore: 6,
    traffic: 5,
    trafficChange: -210,
    kd: 55,
    valueScore: 826.45,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/headless-cms-comparison-2025",
  },
  {
    keyword: "headless cms vs traditional cms",
    volume: 880,
    position: 22,
    positionBefore: 8,
    traffic: 2,
    trafficChange: -95,
    kd: 35,
    valueScore: 401.05,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/headless-cms-comparison-2025",
  },
  {
    keyword: "what is headless cms",
    volume: 6500,
    position: 45,
    positionBefore: 32,
    traffic: 0,
    trafficChange: -5,
    kd: 72,
    valueScore: 2599.9,
    isJunk: true,
    junkReason: "KD > 65 — very high competition, unlikely to recover",
    isSelected: false,
    candidateUrl: "https://www.example-agency.com/blog/headless-cms-comparison-2025",
  },
  {
    keyword: "contentful vs strapi",
    volume: 1200,
    position: 0,
    positionBefore: 12,
    traffic: 0,
    trafficChange: -45,
    kd: 38,
    valueScore: 503.6,
    isJunk: true,
    junkReason: "Brand keyword — covers competitors not related to our services",
    isSelected: false,
    candidateUrl: "https://www.example-agency.com/blog/headless-cms-comparison-2025",
  },
  // For sanity-cms-nextjs-tutorial
  {
    keyword: "sanity cms nextjs tutorial",
    volume: 1100,
    position: 12,
    positionBefore: 3,
    traffic: 8,
    trafficChange: -165,
    kd: 28,
    valueScore: 523.9,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/sanity-cms-nextjs-tutorial",
  },
  {
    keyword: "sanity next.js integration",
    volume: 720,
    position: 14,
    positionBefore: 5,
    traffic: 4,
    trafficChange: -88,
    kd: 22,
    valueScore: 333.9,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/sanity-cms-nextjs-tutorial",
  },
  {
    keyword: "how to use sanity",
    volume: 3200,
    position: 35,
    positionBefore: 28,
    traffic: 0,
    trafficChange: -8,
    kd: 45,
    valueScore: 1287.25,
    isJunk: true,
    junkReason: "Too broad — article covers Next.js integration, not general Sanity usage",
    isSelected: false,
    candidateUrl: "https://www.example-agency.com/blog/sanity-cms-nextjs-tutorial",
  },
  // For seo-ai-content-optimization (intent shifted scenario)
  {
    keyword: "ai seo tools",
    volume: 4800,
    position: 19,
    positionBefore: 5,
    traffic: 3,
    trafficChange: -520,
    kd: 58,
    valueScore: 2183.1,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/seo-ai-content-optimization",
  },
  {
    keyword: "ai content optimization",
    volume: 2200,
    position: 21,
    positionBefore: 7,
    traffic: 1,
    trafficChange: -195,
    kd: 48,
    valueScore: 979.3,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/seo-ai-content-optimization",
  },
  // For cms-migration-guide (all keywords are junk — "Doubtful" case)
  {
    keyword: "cms migration",
    volume: 90,
    position: 16,
    positionBefore: 7,
    traffic: 0,
    trafficChange: -12,
    kd: 32,
    valueScore: 43.4,
    isJunk: true,
    junkReason: "Volume < 100 — insufficient search demand",
    isSelected: false,
    candidateUrl: "https://www.example-agency.com/blog/cms-migration-guide-2025",
  },
  {
    keyword: "website migration checklist",
    volume: 60,
    position: 25,
    positionBefore: 18,
    traffic: 0,
    trafficChange: -3,
    kd: 19,
    valueScore: 26.55,
    isJunk: true,
    junkReason: "Volume < 100 — insufficient search demand",
    isSelected: false,
    candidateUrl: "https://www.example-agency.com/blog/cms-migration-guide-2025",
  },
  // For nextjs-performance-optimization
  {
    keyword: "nextjs performance optimization",
    volume: 1900,
    position: 6,
    positionBefore: 3,
    traffic: 120,
    trafficChange: -95,
    kd: 40,
    valueScore: 808.7,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/nextjs-performance-optimization",
  },
  {
    keyword: "next.js speed optimization",
    volume: 650,
    position: 8,
    positionBefore: 4,
    traffic: 45,
    trafficChange: -60,
    kd: 35,
    valueScore: 291.25,
    isJunk: false,
    junkReason: null,
    isSelected: true,
    candidateUrl: "https://www.example-agency.com/blog/nextjs-performance-optimization",
  },
];

// ── Mock Competitors ──
export const mockCompetitors: Competitor[] = [
  {
    url: "https://hygraph.com/blog/headless-cms-comparison",
    domainRating: 72,
    urlRating: 45,
    estimatedTraffic: 8900,
    newBacklinks90d: 34,
    displacementType: "High authority",
    keyword: "headless cms comparison",
  },
  {
    url: "https://www.g2.com/categories/headless-cms",
    domainRating: 91,
    urlRating: 62,
    estimatedTraffic: 45000,
    newBacklinks90d: 120,
    displacementType: "High authority",
    keyword: "headless cms comparison",
  },
  {
    url: "https://dev.to/alexsmith/headless-cms-comparison-2025-updated",
    domainRating: 88,
    urlRating: 28,
    estimatedTraffic: 3200,
    newBacklinks90d: 15,
    displacementType: "New article",
    keyword: "headless cms comparison",
  },
  {
    url: "https://www.sanity.io/guides/nextjs-sanity-tutorial",
    domainRating: 78,
    urlRating: 55,
    estimatedTraffic: 12000,
    newBacklinks90d: 45,
    displacementType: "Content update",
    keyword: "sanity cms nextjs tutorial",
  },
  {
    url: "https://www.builder.io/blog/ai-seo-tools-review",
    domainRating: 74,
    urlRating: 38,
    estimatedTraffic: 5600,
    newBacklinks90d: 22,
    displacementType: "New article",
    keyword: "ai seo tools",
  },
  {
    url: "https://ahrefs.com/blog/ai-seo",
    domainRating: 92,
    urlRating: 58,
    estimatedTraffic: 28000,
    newBacklinks90d: 89,
    displacementType: "High authority",
    keyword: "ai seo tools",
  },
  {
    url: "https://surferseo.com/blog/ai-content-tools",
    domainRating: 76,
    urlRating: 42,
    estimatedTraffic: 7200,
    newBacklinks90d: 31,
    displacementType: "SERP feature",
    keyword: "ai content optimization",
  },
];

// ── Mock LLM Analysis Results ──
export const mockLLMResults: LLMAnalysis[] = [
  {
    candidateUrl: "https://www.example-agency.com/blog/headless-cms-comparison-2025",
    worsePoints: [
      "Missing 2025/2026 pricing comparisons — competitors have updated pricing tables",
      "No code examples showing API integration for each CMS",
      "Lacks a clear decision matrix or interactive comparison tool",
      "Introduction doesn't address the reader's specific pain point (choosing between options)",
    ],
    strengths: [
      "Good coverage of Sanity-specific features",
      "Clear writing style and structure",
      "Includes migration considerations that competitors skip",
    ],
    whatToAddOrUpdate: [
      {
        section: "Pricing Comparison Table",
        action: "add",
        details: "Add a comprehensive pricing comparison table covering free tiers, per-seat costs, and enterprise pricing for top 8 headless CMS platforms. ~300 words + table.",
        why: "Top 3 competitors all have updated 2026 pricing. This is the #1 missing element.",
      },
      {
        section: "API Code Examples",
        action: "add",
        details: "Add code snippets showing basic content fetching for each CMS (Sanity, Contentful, Strapi, Hygraph). Use TypeScript with Next.js App Router. ~500 words + 4 code blocks.",
        why: "Developer audience expects working code examples. Competitor from dev.to has this.",
      },
      {
        section: "Introduction",
        action: "rewrite",
        details: "Rewrite to address the reader's decision-making pain point directly. Start with 'If you're choosing a headless CMS in 2026...' ~150 words.",
        why: "Current intro is generic. Competitors hook the reader with specific scenarios.",
      },
    ],
    suggestedTitle: "Headless CMS Comparison 2026: Pricing, Features & Code",
    suggestedMeta: "Compare the top 8 headless CMS platforms for 2026. Updated pricing, API code examples, and a decision matrix to pick the right CMS for your Next.js project.",
    updatePlanSummary: "Add pricing table, code examples, and rewrite intro to recover 'headless cms comparison' rankings",
    estimatedEffort: "Medium",
    priority: 1,
    recoveryLikelihood: "High",
    intentShifted: false,
    consolidateWith: null,
    shouldUpdate: "Yes",
  },
  {
    candidateUrl: "https://www.example-agency.com/blog/sanity-cms-nextjs-tutorial",
    worsePoints: [
      "Tutorial uses Pages Router — needs App Router / React Server Components update",
      "Missing GROQ query examples for common patterns",
      "No deployment section (competitors show Vercel deployment)",
      "Images and screenshots are outdated (old Sanity Studio UI)",
    ],
    strengths: [
      "Step-by-step structure is clear and easy to follow",
      "Good explanation of Sanity schema concepts",
    ],
    whatToAddOrUpdate: [
      {
        section: "Full Tutorial",
        action: "rewrite",
        details: "Rewrite using Next.js 16 App Router with Server Components and GROQ. Update all code examples, screenshots. ~2000 words rewrite.",
        why: "Sanity.io's own tutorial now uses App Router. Our Pages Router tutorial is outdated.",
      },
      {
        section: "Deployment to Vercel",
        action: "add",
        details: "Add deployment section with Vercel + environment variables setup. ~400 words.",
        why: "Competitor tutorial includes deployment. Readers want end-to-end guidance.",
      },
    ],
    suggestedTitle: "Sanity CMS + Next.js 16 Tutorial: Build a Blog (2026)",
    suggestedMeta: "Complete tutorial: build a blog with Sanity CMS and Next.js 16 App Router. GROQ queries, Server Components, and Vercel deployment included.",
    updatePlanSummary: "Major rewrite needed: migrate from Pages Router to App Router, update all code examples and screenshots",
    estimatedEffort: "Large",
    priority: 2,
    recoveryLikelihood: "High",
    intentShifted: false,
    consolidateWith: "https://www.example-agency.com/blog/getting-started-sanity-nextjs",
    shouldUpdate: "Yes",
  },
  {
    candidateUrl: "https://www.example-agency.com/blog/seo-ai-content-optimization",
    worsePoints: [
      "Article is informational but top results are now tool reviews / comparisons",
      "Missing hands-on examples with specific AI tools",
      "No data or case studies showing AI-driven SEO improvements",
    ],
    strengths: [
      "Good theoretical foundation on AI in SEO",
      "Well-written and authoritative tone",
    ],
    whatToAddOrUpdate: [
      {
        section: "Entire Article Approach",
        action: "rewrite",
        details: "Search intent has shifted from informational to commercial/comparison. Consider creating a new 'AI SEO Tools Comparison' article instead of updating this one. If updating, pivot to include tool reviews and hands-on examples. ~2500 words.",
        why: "Top 10 results are now dominated by tool reviews (SurferSEO, Ahrefs, Builder.io). Informational content no longer matches search intent.",
      },
    ],
    suggestedTitle: "Best AI SEO Tools 2026: Hands-On Review & Comparison",
    suggestedMeta: "We tested 10 AI SEO tools in 2026. See real results, pricing, and which tool works best for content optimization, keyword research, and technical SEO.",
    updatePlanSummary: "Intent shifted from informational to commercial — recommend creating new comparison article rather than updating existing",
    estimatedEffort: "Large",
    priority: 3,
    recoveryLikelihood: "Low",
    intentShifted: true,
    consolidateWith: null,
    shouldUpdate: "No - intent shifted",
  },
  {
    candidateUrl: "https://www.example-agency.com/blog/cms-migration-guide-2025",
    worsePoints: [
      "All lost keywords have very low search volume (< 100)",
      "Topic is too niche for meaningful organic recovery",
    ],
    strengths: [
      "Comprehensive migration checklist",
      "Good for users who find it through internal links",
    ],
    whatToAddOrUpdate: [],
    suggestedTitle: "CMS Migration Guide 2025",
    suggestedMeta: "Step-by-step CMS migration checklist covering planning, content export, URL mapping, redirects, and post-migration QA.",
    updatePlanSummary: "Low-value keywords — not worth updating for SEO. Keep for internal linking value.",
    estimatedEffort: "Small",
    priority: 5,
    recoveryLikelihood: "Low",
    intentShifted: false,
    consolidateWith: null,
    shouldUpdate: "Doubtful",
  },
  {
    candidateUrl: "https://www.example-agency.com/blog/nextjs-performance-optimization",
    worsePoints: [
      "Missing Next.js 16 Turbopack performance features",
      "No benchmark data comparing optimization techniques",
      "Lacks Core Web Vitals before/after examples",
    ],
    strengths: [
      "Good coverage of image optimization and lazy loading",
      "Practical code examples that work",
      "Strong internal linking to related articles",
    ],
    whatToAddOrUpdate: [
      {
        section: "Turbopack & Next.js 16",
        action: "add",
        details: "Add section covering Turbopack build performance, Cache Components, and new optimization features in Next.js 16. ~400 words.",
        why: "Article is missing the latest framework version. Competitors have updated.",
      },
      {
        section: "Core Web Vitals Benchmarks",
        action: "add",
        details: "Add real before/after screenshots and Lighthouse scores. ~300 words + images.",
        why: "Data-driven content ranks better. Competitor articles include benchmark data.",
      },
    ],
    suggestedTitle: "Next.js 16 Performance Optimization: Complete Guide (2026)",
    suggestedMeta: "Optimize your Next.js 16 app for speed. Turbopack, image optimization, code splitting, and Core Web Vitals benchmarks with before/after results.",
    updatePlanSummary: "Add Next.js 16 Turbopack section and Core Web Vitals benchmarks to regain rankings",
    estimatedEffort: "Medium",
    priority: 2,
    recoveryLikelihood: "High",
    intentShifted: false,
    consolidateWith: null,
    shouldUpdate: "Yes",
  },
];

// ── Mock Ahrefs Upload Files ──
export const mockAhrefsFiles = [
  { name: "organic-keywords-export.csv", size: 245_000, rows: 1842, type: "Organic Keywords" as const },
  { name: "lost-backlinks-90d.csv", size: 78_000, rows: 156, type: "Backlinks" as const },
  { name: "serp-competitors.csv", size: 32_000, rows: 89, type: "Competitor SERP" as const },
];

// ── Processing simulation steps ──
export const mockProcessingSteps = [
  { label: "Fetching article content...", url: "headless-cms-comparison-2025", progress: 10 },
  { label: "Fetching competitor content (3 URLs)...", url: "headless-cms-comparison-2025", progress: 18 },
  { label: "Analyzing with Claude Sonnet...", url: "headless-cms-comparison-2025", progress: 28 },
  { label: "Fetching article content...", url: "sanity-cms-nextjs-tutorial", progress: 35 },
  { label: "Fetching competitor content (1 URL)...", url: "sanity-cms-nextjs-tutorial", progress: 42 },
  { label: "Analyzing with Claude Sonnet...", url: "sanity-cms-nextjs-tutorial", progress: 52 },
  { label: "Fetching article content...", url: "seo-ai-content-optimization", progress: 58 },
  { label: "Fetching competitor content (3 URLs)...", url: "seo-ai-content-optimization", progress: 65 },
  { label: "Analyzing with Claude Sonnet...", url: "seo-ai-content-optimization", progress: 75 },
  { label: "Fetching article content...", url: "nextjs-performance-optimization", progress: 80 },
  { label: "Analyzing with Claude Sonnet...", url: "nextjs-performance-optimization", progress: 90 },
  { label: "Generating Excel report...", url: "", progress: 95 },
  { label: "Complete!", url: "", progress: 100 },
];
